In [ ]:
import numpy as np

a = np.array([1, 2, 3]) # torch 的转化张量的方法为 torch.tensor()，转化为 numpy 数组的方法为 numpy.array()
print(a.shape, a.ndim)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape, a.ndim)

a = np.array([[1, 2, 3]])
print(a.shape, a.ndim)

print(len(a.shape) == a.ndim)

(3,) 1
(3, 3) 2
(1, 3) 2
True


In [ ]:
import math

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.size, math.prod(b.shape))  # torch 没有 size 属性，其中的 size() 是方法，shape 返回的就是这个方法，二者完全等价，numel() 方法等价于 numpy 是 size 属性
print(np.prod((1, 2, 3, 5)), b.dtype) # torch.prod() 方法只接受参数为 tensor 的数据类型，numpy 接受 tuple 类型

b = b.astype(float)  # torch 与 numpy 转换元素数据类型所使用方法不同，前者使用 astype 方法，后者直接转化
# 也可创建的时候直接指定类型 b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=float)
print(b, b.dtype)

6 6
30 int64
[[1. 2. 3.]
 [4. 5. 6.]] float64


In [ ]:
c = np.ones(3)
print(c, c.shape)
c = np.ones((1, 3))
print(c, c.shape)

[1. 1. 1.] (3,)
[[1. 1. 1.]] (1, 3)


In [ ]:
d = [i for i in range(1, 13)]
d = np.array(d)

d1 = d.reshape((2, 2, -1))
print(d1, d1.shape)
1
d2 =  d.reshape((3, -1))
print(d2, d2.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
e = np.arange(10)
print(e, e.shape)

e = np.arange(10, 20)
print(e, e.shape)

e = np.arange(10, 21, 2)
print(e, e.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[10 11 12 13 14 15 16 17 18 19] (10,)
[10 12 14 16 18 20] (6,)


In [6]:
f = np.ones(10)
print(f, f.shape)

f = np.zeros(10)
print(f, f.shape)

f = np.empty(10)
print(f, f.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)


In [ ]:
g = np.linspace(10, 20, 15)
print(g, g.shape)

[10.         10.71428571 11.42857143 12.14285714 12.85714286 13.57142857
 14.28571429 15.         15.71428571 16.42857143 17.14285714 17.85714286
 18.57142857 19.28571429 20.        ] (15,)


In [ ]:
h = np.array([[3, 1, 2, 4], [2, 1, 5, 4], [8, 7, 9, 6], [9, 3, 4, 1], [1, 3, 8, 2]])
print(h, h.shape)

h1 = h.reshape((1, -1)) 
h1 = np.sort(h1)  # torch 返回值是一个 tuple，(value, indices)，代表排序后的值和排序前的下标
print(h1)

h2 = h
h2 = np.sort(h2, axis=0) # torch 轴参数一般写为 dim，numpy 写为 axis，默认为 -1 按照最后一个维度排序
print(h2)

h3 = h.reshape((2, 2, -1))
print(h3, h3.shape)

h4 = h3
h4 = np.sort(h4, axis=-1)
print(h4, h4.shape)


[[3 1 2 4]
 [2 1 5 4]
 [8 7 9 6]
 [9 3 4 1]
 [1 3 8 2]] (5, 4)
[[1 1 1 1 2 2 2 3 3 3 4 4 4 5 6 7 8 8 9 9]]
[[1 1 2 1]
 [2 1 4 2]
 [3 3 5 4]
 [8 3 8 4]
 [9 7 9 6]]
[[[3 1 2 4 2]
  [1 5 4 8 7]]

 [[9 6 9 3 4]
  [1 1 3 8 2]]] (2, 2, 5)
[[[1 2 2 3 4]
  [1 4 5 7 8]]

 [[3 4 6 9 9]
  [1 1 2 3 8]]] (2, 2, 5)


In [ ]:
i = np.array([[1, 2], [3, 4]])
j = np.array([[5, 6], [7, 8]])

i = np.concatenate((i, j), axis=-1) # torch 轴参数为 dim，numpy 轴参数为 axis，torch 的 cat() 方法与 numpy 的 concatenate() 方法有一样的效果
print(i, i.shape)

[[1 2 5 6]
 [3 4 7 8]] (2, 4)


In [ ]:
# torch 的 randint() 和 normal() 方法都不接受向量类型的参数，也就是一维的 numpy 数组
k = 40 * np.random.random(10) + 60 # torch 的 rand() 方法与 numpy 的 random.random() 方法有一样的效果
print(k, k.shape)

k = np.random.randint(1, 10, (3, 3)) # torch 的 randint() 方法与 numpy 的 random.randint() 方法有一样的效果
print(k, k.shape)

k = np.random.normal(0, 1, (2, 3)) # torch 的 normal() 方法与 numpy 的 random.normal() 方法有一样的效果
print(k, k.shape)

k = np.random.randn(2, 3) # torch 的 randn() 方法与 numpy 的 random.randn() 方法有一样的效果
print(k, k.shape)

[61.1963156  77.77120822 61.5454976  65.60899095 90.34240107 73.03116735
 77.40856847 78.79810204 96.75897514 66.58395263] (10,)
[[6 3 9]
 [1 1 2]
 [3 5 7]] (3, 3)
[[ 0.99626141 -0.47596991 -1.8375531 ]
 [-0.35660089 -1.35998422  1.3092691 ]] (2, 3)
[[-1.73422544 -2.45405005  1.84580967]
 [ 0.28095907  0.72451289 -0.33716197]] (2, 3)


In [ ]:
m = np.array([[3, 1, 2, 4], [2, 1, 5, 4], [8, 7, 9, 6], [9, 3, 4, 1], [1, 3, 8, 2]])
m1 = m[[0, 1, 2], [0, 1, 2]]
print(m1, m1.shape)

m[[0, 1, 2], [0, 1, 2]] = 100
print(m, m.shape)

[3 1 9] (3,)
[[100   1   2   4]
 [  2 100   5   4]
 [  8   7 100   6]
 [  9   3   4   1]
 [  1   3   8   2]] (5, 4)


In [ ]:
n = np.arange(1, 11)
print(n, n.shape)

n1 = n[2:-2]
print(n1, n1.shape)

n2 = n[::2]
print(n2, n2.shape)

n3 = n[1:-1:2]
print(n3, n3.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)
[3 4 5 6 7 8] (6,)
[1 3 5 7 9] (5,)
[2 4 6 8] (4,)


In [7]:
o = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(o[::2, ::2])

print(o[2], o[2, :])

print(o[:, 2].reshape(1, -1).T) # 直接输出 o[:, 2] 是一个向量不是列矩阵，采用本方法转化，截取列大于 1，就会自动转化为列矩阵，等价于 o[:, 2].reshape(-1, 1)
print(o[:, 1:])

[[1 3]
 [7 9]]
[7 8 9] [7 8 9]
[[3]
 [6]
 [9]]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
p = np.arange(1, 11)
p1 = p[1:5]
p1[0] = 100
print(p, p.shape)

p2 = p[1:5].copy()  # torch 的 clone() 方法和 numpy 的 copy() 方法有相同的效果
p2[0] = 1000
print(p, p.shape)

p3 = p
p3[0] = 1000
print(p, p.shape)

p4 = p.copy()
p4[0] = 10000
print(p, p.shape)

[  1 100   3   4   5   6   7   8   9  10] (10,)
[  1 100   3   4   5   6   7   8   9  10] (10,)
[1000  100    3    4    5    6    7    8    9   10] (10,)
[1000  100    3    4    5    6    7    8    9   10] (10,)


In [ ]:
q = np.arange(1, 11)
q = np.flipud(q)
print(q, q.shape)

[10  9  8  7  6  5  4  3  2  1] (10,)


In [ ]:
r = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rud = np.flipud(r)
rlr = np.fliplr(r)
print(rud, rud.shape)
print(rlr, rlr.shape)

[[7 8 9]
 [4 5 6]
 [1 2 3]] (3, 3)
[[3 2 1]
 [6 5 4]
 [9 8 7]] (3, 3)


In [ ]:
s = np.arange(1, 11)

s1, s2, s3 = np.split(s, [2, 8]) # torch 的 split() 方法用起来和 numpy 的完全不一样，前者需要手动的指定块的大小，如果是一个值的话代表等分，后者代表切割的位置
# 块的大小的加和要严格的相等，需要手动算一下，不能等于吧最后一个维度留作 -1， 除非等分的时候，最后不足才会自动切割
print(s1, s2, s3)
s1[0] = 100
print(s)

s = s.reshape((2, -1))
s1, s2 = np.split(s, [1], axis=0)
print(s1, s2)

s1, s2 = np.split(s, [1], axis=1)
print(s1)
print(s2)

[1 2] [3 4 5 6 7 8] [ 9 10]
[100   2   3   4   5   6   7   8   9  10]
[[100   2   3   4   5]] [[ 6  7  8  9 10]]
[[100]
 [  6]]
[[ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
t = np.arange(1, 5)
print(t ** 3)

t1 = -t
print(t)
t1[0] = 100
print(t)

[ 1  8 27 64]
[1 2 3 4]
[1 2 3 4]


In [ ]:
u1 = np.arange(0, 5)
u2 = np.arange(0, 15).reshape(3, -1)
u3 = np.arange(0, 3)

print(u1)
print(u2)
print(u3)
# 广播和矩阵乘法没有任何关系，广播成 (x, y) 大小，逐元素相乘而已，左乘本身要是 (1, y)，右乘本身要是 (x, 1)

print(u1 * u2)
print(u3.reshape(-1, 1) * u2)

# 当形状为 (1, y) 和 (x, 1) 相乘，都广播为大小 (x, y) 逐元素相乘

print(u1 * u3.reshape(-1, 1))

[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2]
[[ 0  1  4  9 16]
 [ 0  6 14 24 36]
 [ 0 11 24 39 56]]
[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [20 22 24 26 28]]
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [ ]:
v1 = np.arange(0, 5)
v2 = np.arange(0, 5)

print(np.dot(v1, v2)) # 矩阵乘法混有向量的时候，根据需求自动的充当行矩阵或者列矩阵，混有向量的时候输出结果一定是向量
# torch 使用 dot 的时候，必须保证两个全是向量

v3 = np.arange(0, 15).reshape(5, -1)
print(np.dot(v1, v3))  # torch 向量乘向量的时候可以使用 dot() 方法，但是只要两者之间出现矩阵，就必须使用 matmul() 方法，当然向量之间的乘法也可以使用 matmul() 方法

v4 = np.arange(0, 10).reshape(5, -1)
v5 = np.arange(0, 16).reshape(2, -1)

print(np.dot(v4, v5))

30
[ 90 100 110]
[[  8   9  10  11  12  13  14  15]
 [ 24  29  34  39  44  49  54  59]
 [ 40  49  58  67  76  85  94 103]
 [ 56  69  82  95 108 121 134 147]
 [ 72  89 106 123 140 157 174 191]]


In [ ]:
w = np.array([1, 2, -3])

print(np.abs(w))
print(np.sin(w), np.cos(w), np.tan(w))

w1 = np.array([1, 2, 3])
print(np.exp(w1), 2 ** w1, 10 ** w1) # torch 的 exp() 函数必须传入张量类型 

w2 = np.array([1, 10, 100, 1000])
print(np.log(w2), np.log(w2) / np.log(2), np.log(w2) / np.log(10))
# torch 的 log() 函数必须传入张量类型



[1 2 3]
[ 0.84147098  0.90929743 -0.14112001] [ 0.54030231 -0.41614684 -0.9899925 ] [ 1.55740772 -2.18503986  0.14254654]
[ 2.71828183  7.3890561  20.08553692] [2 4 8] [  10  100 1000]
[0.         2.30258509 4.60517019 6.90775528] [0.         3.32192809 6.64385619 9.96578428] [0. 1. 2. 3.]


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]]) 

print(np.max(x, axis=0), np.max(x, axis=1)) # torch 的 max 函数也会返回最大值和最大值的位置
print(np.sum(x, axis=0), np.sum(x, axis=1))
print(np.prod(x, axis=0), np.prod(x, axis=1))
print(np.mean(x, axis=0), np.std(x, axis=0)) # torch 里面的 mean()、std() 函数只接受浮点类型的数组

# nanmax ... 忽略缺失值

[4 5 6] [3 6]
[5 7 9] [ 6 15]
[ 4 10 18] [  6 120]
[2.5 3.5 4.5] [1.5 1.5 1.5]


In [ ]:
y = np.random.normal(0, 1, (10000, ))

print(np.sum(np.abs(y) <= 1))

y1 = np.array([1, 2, 3])
y2 = np.array([3, 4, 3])
print(y1 == y2, np.any(y1 == y2), np.all(y1 == y2))

6809
[False False  True] True False


In [ ]:
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

z1 = z >= 4
print(z[z1], np.where(z1)) # 矩阵进行掩码操作变化为了向量

[4 5 6 7 8 9] (array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))
