In [1]:
import torch

a = torch.tensor([1, 2, 3]) # torch 的转化张量的方法为 torch.tensor()，转化为 numpy 数组的方法为 numpy.array()
print(a.shape, a.ndim)

a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape, a.ndim)

a = torch.tensor([[1, 2, 3]])
print(a.shape, a.ndim)

print(len(a.shape) == a.ndim)

torch.Size([3]) 1
torch.Size([3, 3]) 2
torch.Size([1, 3]) 2
True


In [2]:
import math

b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=float)
print(b.numel(), math.prod(b.shape))  # torch 没有 size 属性，其中的 size() 是方法，shape 返回的就是这个方法，二者完全等价，numel() 方法等价于 numpy 是 size 属性
print(torch.prod(torch.tensor((1, 2, 3, 5))), b.dtype) # torch.prod() 方法只接受参数为 tensor 的数据类型，numpy 接受 tuple 类型

b = b.float()  # torch 与 numpy 转换元素数据类型所使用方法不同，前者使用 astype 方法，后者直接转化
# 也可创建的时候直接指定类型 b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=float)
print(b, b.dtype)

6 6
tensor(30) torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.float32


In [3]:
c = torch.ones(3)
print(c, c.shape)
c = torch.ones((1, 3))
print(c, c.shape)

tensor([1., 1., 1.]) torch.Size([3])
tensor([[1., 1., 1.]]) torch.Size([1, 3])


In [4]:
d = [i for i in range(1, 13)]
d = torch.tensor(d)

d1 = d.reshape((2, 2, -1))
print(d1, d1.shape)
1
d2 =  d.reshape((3, -1))
print(d2, d2.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) torch.Size([2, 2, 3])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]) torch.Size([3, 4])


In [5]:
e = torch.arange(10)
print(e, e.shape)

e = torch.arange(10, 20)
print(e, e.shape)

e = torch.arange(10, 21, 2)
print(e, e.shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) torch.Size([10])
tensor([10, 12, 14, 16, 18, 20]) torch.Size([6])


In [6]:
f = torch.ones(10)
print(f, f.shape)

f = torch.zeros(10)
print(f, f.shape)

f = torch.empty(10)
print(f, f.shape)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([10])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) torch.Size([10])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]) torch.Size([10])


In [7]:
g = torch.linspace(10, 20, 15)
print(g, g.shape)

tensor([10.0000, 10.7143, 11.4286, 12.1429, 12.8571, 13.5714, 14.2857, 15.0000,
        15.7143, 16.4286, 17.1429, 17.8571, 18.5714, 19.2857, 20.0000]) torch.Size([15])


In [8]:
h = torch.tensor([[3, 1, 2, 4], [2, 1, 5, 4], [8, 7, 9, 6], [9, 3, 4, 1], [1, 3, 8, 2]])
print(h, h.shape)

h1 = h.reshape((1, -1))
h1, _ = torch.sort(h1) # torch 返回值是一个 tuple，(value, indices)，代表排序后的值和排序前的下标
print(h1)

h2 = h
h2, _ = torch.sort(h2, dim=0) # torch 轴参数一般写为 dim，numpy 写为 axis，默认为 -1 按照最后一个维度排序
print(h2)

h3, _ = h.reshape((2, 2, -1))
print(h3, h3.shape)

h4 = h3
h4, _ = torch.sort(h4, dim=-1)
print(h4, h4.shape)


tensor([[3, 1, 2, 4],
        [2, 1, 5, 4],
        [8, 7, 9, 6],
        [9, 3, 4, 1],
        [1, 3, 8, 2]]) torch.Size([5, 4])
tensor([[1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 6, 7, 8, 8, 9, 9]])
tensor([[1, 1, 2, 1],
        [2, 1, 4, 2],
        [3, 3, 5, 4],
        [8, 3, 8, 4],
        [9, 7, 9, 6]])
tensor([[3, 1, 2, 4, 2],
        [1, 5, 4, 8, 7]]) torch.Size([2, 5])
tensor([[1, 2, 2, 3, 4],
        [1, 4, 5, 7, 8]]) torch.Size([2, 5])


In [9]:
i = torch.tensor([[1, 2], [3, 4]])
j = torch.tensor([[5, 6], [7, 8]])

i = torch.cat((i, j), dim=-1) # torch 轴参数为 dim，numpy 轴参数为 axis，torch 的 cat() 方法与 numpy 的 concatenate() 方法有一样的效果
print(i, i.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


In [10]:
# torch 的 randint() 和 normal() 方法都不接受向量类型的参数，也就是一维的 numpy 数组
k = 40 * torch.rand(10) + 60 # torch 的 rand() 方法与 numpy 的 random.random() 方法有一样的效果
print(k, k.shape)

k = torch.randint(1, 10, (3, 3)) # torch 的 randint() 方法与 numpy 的 random.randint() 方法有一样的效果
print(k, k.shape)

k = torch.normal(0, 1, (2, 3)) # torch 的 normal() 方法与 numpy 的 random.normal() 方法有一样的效果
print(k, k.shape)

k = torch.randn(2, 3) # torch 的 randn() 方法与 numpy 的 random.randn() 方法有一样的效果
print(k, k.shape)

tensor([61.2704, 97.2332, 78.3140, 91.9332, 95.4287, 87.9820, 98.7736, 90.9288,
        78.8261, 62.9807]) torch.Size([10])
tensor([[2, 4, 7],
        [8, 4, 9],
        [8, 1, 3]]) torch.Size([3, 3])
tensor([[ 1.6986, -0.6187,  0.3423],
        [ 0.7636, -0.4389, -0.1773]]) torch.Size([2, 3])
tensor([[ 0.7433, -0.2108,  0.5234],
        [ 0.1672,  0.6574,  0.0608]]) torch.Size([2, 3])


In [11]:
m = torch.tensor([[3, 1, 2, 4], [2, 1, 5, 4], [8, 7, 9, 6], [9, 3, 4, 1], [1, 3, 8, 2]])
m1 = m[[0, 1, 2], [0, 1, 2]]
print(m1, m1.shape)

m[[0, 1, 2], [0, 1, 2]] = 100
print(m, m.shape)

tensor([3, 1, 9]) torch.Size([3])
tensor([[100,   1,   2,   4],
        [  2, 100,   5,   4],
        [  8,   7, 100,   6],
        [  9,   3,   4,   1],
        [  1,   3,   8,   2]]) torch.Size([5, 4])


In [12]:
n = torch.arange(1, 11)
print(n, n.shape)

n1 = n[2:-2]
print(n1, n1.shape)

n2 = n[::2]
print(n2, n2.shape)

n3 = n[1:-1:2]
print(n3, n3.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
tensor([3, 4, 5, 6, 7, 8]) torch.Size([6])
tensor([1, 3, 5, 7, 9]) torch.Size([5])
tensor([2, 4, 6, 8]) torch.Size([4])


In [13]:
o = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(o[::2, ::2])

print(o[2], o[2, :])

print(o[:, 2].reshape(1, -1).T) # 直接输出 o[:, 2] 是一个向量不是列矩阵，采用本方法转化，截取列大于 1，就会自动转化为列矩阵，等价于 o[:, 2].reshape(-1, 1)
print(o[:, 1:])

tensor([[1, 3],
        [7, 9]])
tensor([7, 8, 9]) tensor([7, 8, 9])
tensor([[3],
        [6],
        [9]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [14]:
p = torch.arange(1, 11)
p1 = p[1:5]
p1[0] = 100
print(p, p.shape)

p2 = p[1:5].clone() # torch 的 clone() 方法和 numpy 的 copy() 方法有相同的效果
p2[0] = 1000
print(p, p.shape)

p3 = p
p3[0] = 1000
print(p, p.shape)

p4 = p.clone()
p4[0] = 10000
print(p, p.shape)

tensor([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10]) torch.Size([10])
tensor([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10]) torch.Size([10])
tensor([1000,  100,    3,    4,    5,    6,    7,    8,    9,   10]) torch.Size([10])
tensor([1000,  100,    3,    4,    5,    6,    7,    8,    9,   10]) torch.Size([10])


In [15]:
q = torch.arange(1, 11)
q = torch.flipud(q)
print(q, q.shape)

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]) torch.Size([10])


In [16]:
r = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

rud = torch.flipud(r)
rlr = torch.fliplr(r)
print(rud, rud.shape)
print(rlr, rlr.shape)

tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]) torch.Size([3, 3])
tensor([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]) torch.Size([3, 3])


In [17]:
s = torch.arange(1, 11)

s1, s2, s3 = torch.split(s, [2, 6, 2]) # torch 的 split() 方法用起来和 numpy 的完全不一样，前者需要手动的指定块的大小，如果是一个值的话代表等分，后者代表切割的位置
# 块的大小的加和要严格的相等，需要手动算一下，不能等于吧最后一个维度留作 -1， 除非等分的时候，最后不足才会自动切割
print(s1, s2, s3)
s1[0] = 100
print(s)

s = s.reshape((2, -1))
s1, s2 = torch.split(s, [1, 1], dim=0)
print(s1, s2)

s1, s2 = torch.split(s, [1, 4], dim=1)
print(s1)
print(s2)

tensor([1, 2]) tensor([3, 4, 5, 6, 7, 8]) tensor([ 9, 10])
tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])
tensor([[100,   2,   3,   4,   5]]) tensor([[ 6,  7,  8,  9, 10]])
tensor([[100],
        [  6]])
tensor([[ 2,  3,  4,  5],
        [ 7,  8,  9, 10]])


In [18]:
t = torch.arange(1, 5)
print(t ** 3)

t1 = -t
print(t)
t1[0] = 100
print(t)

tensor([ 1,  8, 27, 64])
tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])


In [19]:
u1 = torch.arange(0, 5)
u2 = torch.arange(0, 15).reshape(3, -1)
u3 = torch.arange(0, 3)

print(u1)
print(u2)
print(u3)
# 广播和矩阵乘法没有任何关系，广播成 (x, y) 大小，逐元素相乘而已，左乘本身要是 (1, y)，右乘本身要是 (x, 1)

print(u1 * u2)
print(u3.reshape(-1, 1) * u2)

# 当形状为 (1, y) 和 (x, 1) 相乘，都广播为大小 (x, y) 逐元素相乘

print(u1 * u3.reshape(-1, 1))

tensor([0, 1, 2, 3, 4])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([0, 1, 2])
tensor([[ 0,  1,  4,  9, 16],
        [ 0,  6, 14, 24, 36],
        [ 0, 11, 24, 39, 56]])
tensor([[ 0,  0,  0,  0,  0],
        [ 5,  6,  7,  8,  9],
        [20, 22, 24, 26, 28]])
tensor([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4],
        [0, 2, 4, 6, 8]])


In [20]:
v1 = torch.arange(0, 5)
v2 = torch.arange(0, 5)

print(torch.dot(v1, v2)) # 矩阵乘法混有向量的时候，根据需求自动的充当行矩阵或者列矩阵，混有向量的时候输出结果一定是向量
# torch 使用 dot 的时候，必须保证两个全是向量

v3 = torch.arange(0, 15).reshape(5, -1)
print(torch.matmul(v1, v3)) # torch 向量乘向量的时候可以使用 dot() 方法，但是只要两者之间出现矩阵，就必须使用 matmul() 方法，当然向量之间的乘法也可以使用 matmul() 方法

# 除此之外，向量和矩阵的乘积可以使用 mv() 方法，矩阵和矩阵的乘积可以使用 mm() 方法，matmul() 方法是万能的

v4 = torch.arange(0, 10).reshape(5, -1)
v5 = torch.arange(0, 16).reshape(2, -1)

print(torch.mm(v4, v5))

tensor(30)
tensor([ 90, 100, 110])
tensor([[  8,   9,  10,  11,  12,  13,  14,  15],
        [ 24,  29,  34,  39,  44,  49,  54,  59],
        [ 40,  49,  58,  67,  76,  85,  94, 103],
        [ 56,  69,  82,  95, 108, 121, 134, 147],
        [ 72,  89, 106, 123, 140, 157, 174, 191]])


In [21]:
w = torch.tensor([1, 2, -3])

print(torch.abs(w))
print(torch.sin(w), torch.cos(w), torch.tan(w))

w1 = torch.tensor([1, 2, 3])
print(torch.exp(w1), 2 ** w1, 10 ** w1) # torch 的 exp() 函数必须传入张量类型 

w2 = torch.tensor([1, 10, 100, 1000])
print(torch.log(w2), torch.log(w2) / torch.log(torch.tensor(2)), torch.log(w2) / torch.log(torch.tensor(10)))
# torch 的 log() 函数必须传入张量类型



tensor([1, 2, 3])
tensor([ 0.8415,  0.9093, -0.1411]) tensor([ 0.5403, -0.4161, -0.9900]) tensor([ 1.5574, -2.1850,  0.1425])
tensor([ 2.7183,  7.3891, 20.0855]) tensor([2, 4, 8]) tensor([  10,  100, 1000])
tensor([0.0000, 2.3026, 4.6052, 6.9078]) tensor([0.0000, 3.3219, 6.6439, 9.9658]) tensor([0., 1., 2., 3.])


In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]).float()

print(torch.max(x, dim=0)[0], torch.max(x, dim=1)[0]) # torch 的 max 函数也会返回最大值和最大值的位置
print(torch.sum(x, dim=0), torch.sum(x, dim=1))
print(torch.prod(x, dim=0), torch.prod(x, dim=1))
print(torch.mean(x, dim=0), torch.std(x, dim=0)) # torch 里面的 mean()、std() 函数只接受浮点类型的数组

# nanmax ... 忽略缺失值

tensor([4., 5., 6.]) tensor([3., 6.])
tensor([5., 7., 9.]) tensor([ 6., 15.])
tensor([ 4., 10., 18.]) tensor([  6., 120.])
tensor([2.5000, 3.5000, 4.5000]) tensor([2.1213, 2.1213, 2.1213])


In [23]:
y = torch.normal(0, 1, (10000, ))

print(torch.sum(torch.abs(y) <= 1))

y1 = torch.tensor([1, 2, 3])
y2 = torch.tensor([3, 4, 3])
print(y1 == y2, torch.any(y1 == y2), torch.all(y1 == y2))

tensor(6822)
tensor([False, False,  True]) tensor(True) tensor(False)


In [24]:
z = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

z1 = z >= 4
print(z[z1], torch.where(z1)) # 矩阵进行掩码操作变化为了向量

tensor([4, 5, 6, 7, 8, 9]) (tensor([1, 1, 1, 2, 2, 2]), tensor([0, 1, 2, 0, 1, 2]))
